name: hackathon-db

type: 'nodejs:16.16.0'

disk: 512

dependencies:
    nodejs:
        yarn: "*"

relationships:
    mongodatabase: 'dbmongo:mongodb'

web:
    commands:
        start: node src/index.js